### ISSUE TITLE
Maps SDK for Android version

### ISSUE THREAD

**Issue by AjayChauhan-Artesian** [themronion/Maui.GoogleMaps#30]
I have received a mail from Google Team regarding the Maps SDK Android version. As I'm using your Onion Google Maps in my app I need to know which version of Maps SDK are you using within the package.

I have received this from Google - "You may have projects using the legacy renderer that will be decommissioned by March 3, 2025. Apps built with the Maps SDK for Android will be automatically updated to the latest renderer beginning March 4, 2024."

What I need to do?

**Comment by themronion** [comment]
> What I need to do?

Nothing, enjoy your life and be happy :)
The lib already uses the latest renderer:
https://github.com/themronion/Maui.GoogleMaps/blob/1d94a8778ed793fda17f9d1380edc6859c0b619b/lib/Maui.GoogleMaps/Platforms/Android/MauiGoogleMaps.cs#L35

Probably you are receiving this email because of Xamarin apps that you have
