### ISSUE TITLE
iOS support policy - google maps

### ISSUE THREAD

**Issue by plppp2001** [themronion/Maui.GoogleMaps#49]
Just a heads up, I received this info; Not urgent just letting everyone know;

https://developers.google.com/maps/software-support#ios-support-policy

![image](https://github.com/themronion/Maui.GoogleMaps/assets/45370058/40695e60-b407-4a0b-af38-bae06124ed2a)

**Comment by codercampos** [comment]
I would suggest to add a disclaimer that the library will only be supportef from iOS 16.

**Comment by themronion** [comment]
This is not true, the native sdk binding that is shipped with my library is quite old, so it supports old versions. No action is required here.
Unless someone really wants to update the native bindings, since xamarin team archived the repo with those bindings) Then, after the update that message definitely will be appropriate for this lib

**Comment by codercampos** [comment]
I didn't properly read that says **2025**. Sorry to provoque noise on this one.

**Comment by plppp2001** [comment]
Thanks for bouble checking.
